# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 08:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentExpiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2019, 1, 2, 8, 33, 19, 526685))),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contentexpiry',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
